# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_num', models.CharField(choices=[(b'A', b'Block-A'), (b'B', b'Block-B'), (b'C', b'Block-C')], default=b'A', max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_num', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('accommodation', models.CharField(choices=[(b'S', b'Single'), (b'D', b'Double'), (b'T', b'Triple')], default=b'T', max_length=10)),
                ('status', models.CharField(blank=True, choices=[(b'A', b'Available'), (b'NA', b'Not Available')], help_text=b'Room Availability', max_length=2)),
                ('block_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.Block')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('roll_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=200)),
                ('m_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('fee_receipt', models.CharField(max_length=20, null=True)),
                ('per_address', models.TextField(null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('room_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.Room')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
